EscolaLMS/Admin

- README.md
- cypress/integration/routes.ts
- cypress/support/commands.ts
- package.json
> cypress e2e recording. additional tests

- config/routes.ts
- package.json
- src/components/H5PContentSelect/index.tsx
- src/components/ProgramForm/Topic/index.tsx
- src/components/ProgramForm/Topic/media/h5p.tsx
- src/locales/en-US.ts
- src/pages/Courses/form.tsx
- src/pages/H5P/form.tsx
- src/pages/H5P/index.tsx
- src/services/escola-lms/h5p.ts
- src/services/escola-lms/typings.d.ts
> h5p elements

- config/routes.ts
- src/components/ProgramForm/Topic/media/h5p.tsx
- src/pages/Courses/form.tsx
- src/pages/H5P/index.tsx
- src/pages/H5P/preview.css
- src/pages/H5P/preview.tsx
> h5p preview

- package.json
- src/components/ProgramForm/Lesson/form.tsx
- src/components/ProgramForm/Lesson/index.tsx
- src/components/ProgramForm/Topic/form.tsx
- src/components/ProgramForm/Topic/index.tsx
- src/components/WysiwygMarkdown/index.tsx
- src/pages/Courses/form.tsx
- src/services/escola-lms/typings.d.ts
> lesson, topic missing fields #45, #46

- src/components/ProgramForm/Lesson/form.tsx
- src/components/ProgramForm/Lesson/index.tsx
- src/components/ProgramForm/Topic/index.tsx
- src/components/ProgramForm/Topic/media/text.tsx
- src/components/WysiwygMarkdown/index.css
- src/components/WysiwygMarkdown/index.tsx
- src/pages/Courses/form.tsx
> wysiwyg fixes 

- src/pages/Orders/index.tsx
- src/pages/Payments/index.tsx
> date range

- src/components/RightContent/AvatarDropdown.tsx
- src/services/escola-lms/login.ts
- src/services/escola-lms/typings.d.ts
https://github.com/EscolaLMS/Admin/issues/117
> fix: logout endpoints

- src/components/ProgramForm/Topic/index.tsx
- src/components/SecureUpload/index.tsx
> upload file fix

- src/pages/Categories/index.tsx
> change enum

- src/pages/Users/User/form.tsx
- src/services/escola-lms/typings.d.ts
- src/services/escola-lms/user.ts
> delete button  user avatar

- src/components/ProgramForm/Topic/media/h5p.tsx
- src/pages/Courses/index.tsx
- src/pages/Notifications/index.tsx
- src/services/escola-lms/course.ts
- src/services/escola-lms/notifications.ts
> add status filter, add data filter

- src/components/ConsultationRow/index.tsx
- src/components/ProFormImageUpload/index.tsx
- src/components/StationaryEventRow/index.tsx
- src/components/TypeButton/index.tsx
- src/components/TypeButtonDrawer/index.tsx
- src/components/TypeDrawer/index.tsx
- src/components/WebinarRow/index.tsx
- src/locales/en-US.ts
- src/locales/pl-PL.ts
- src/pages/Products/components/form.tsx
- src/pages/Products/index.tsx
- src/services/escola-lms/products.ts
- src/services/escola-lms/typings.d.ts
> product listsing filters & fixes STAR-613

- src/components/CategoryCheckboxTree/index.tsx
- src/components/ProFormImageUpload/index.tsx
- src/components/Tags/index.tsx
- src/locales/en-US.ts
- src/locales/pl-PL.ts
- src/pages/Products/components/form.tsx
> missing fields STAR-621

- src/components/UserSelect/index.tsx
- src/pages/Products/components/form.tsx
> find uyser by email

- src/components/ProductWidget/index.tsx
- src/locales/en-US.ts
- src/locales/pl-PL.ts
- src/pages/Consultations/form.tsx
- src/pages/Products/components/UserAccess.tsx
- src/pages/Products/components/form.tsx
> change term date

- src/components/ProgramForm/ThreeColProgram/LessonForm/form.tsx
- src/components/ProgramForm/ThreeColProgram/TopicForm/index.tsx
> bugfixes - clone button

- src/locales/en-US.ts
- src/locales/pl-PL.ts
- src/pages/Courses/index.tsx
I forgot to add the translation, it has been corrected here
> LMSDEMO-459 - Link to guide

- src/components/LogsWidget/index.tsx
- src/services/escola-lms/tracker.ts
resolves https://github.com/EscolaLMS/Admin/issues/457
> LMSDEMO-457 - search by path in logs

- src/pages/Users/index.css
closes https://github.com/EscolaLMS/Admin/issues/607
> LMSDEMO-607 - equal columns

- src/components/ProgramForm/ThreeColProgram/TopicForm/descriptionModal.tsx
closes https://github.com/EscolaLMS/Admin/issues/548
> LMSDEMO-548 - editor columns

- src/pages/Welcome.tsx
https://escl24.atlassian.net/browse/LMSDEMO-469
> Add token to authorize login to platform

- src/pages/Vouchers/form.tsx
closes https://github.com/EscolaLMS/Admin/issues/570
> LMSDEMO-570 - voucher wrong url

- src/components/UserSelect/index.tsx
closes https://github.com/EscolaLMS/Admin/issues/345
> LMSDEMO-345 - unselect user

- src/pages/Settings/global.tsx
https://escl24.atlassian.net/browse/LMSDEMO-470
> Add dynamic update of global setting

- src/pages/Courses/form.tsx
closes https://github.com/EscolaLMS/Admin/issues/535
closes https://github.com/EscolaLMS/Admin/issues/536
> LMSDEMO-535 - fixed width of fields

- src/pages/Courses/form.tsx
- src/services/escola-lms/typings.d.ts
closes https://github.com/EscolaLMS/Admin/issues/487
> LMSDEMO-487 - clear date

- src/components/Dashboard/index.tsx
https://escl24.atlassian.net/browse/LMSDEMO-552
> Save layout to Local Storage on change

- src/components/H5P/editor.tsx
https://escl24.atlassian.net/browse/LMSDEMO-610
> Fix h5p query language issue

- src/pages/Settings/components/PackageModalForm.tsx
- src/pages/Settings/components/SettingsValue.tsx
- src/pages/Settings/package.tsx
closes https://github.com/EscolaLMS/Admin/issues/573
> LMSDEMO-573 - package settings

- src/pages/User/login/index.tsx
https://escl24.atlassian.net/browse/WC-590
Zostały defaultowe placeholdery czyli 'Please enter'
> Remove placeholders in login inputs

- src/components/ProgramForm/ThreeColProgram/TopicForm/index.tsx
- src/components/ProgramForm/ThreeColProgram/TopicForm/media/index.css
- src/components/ProgramForm/ThreeColProgram/TopicForm/media/upload.tsx
- src/components/ProgramForm/ThreeColProgram/index.tsx
https://escl24.atlassian.net/browse/WC-610
> Fix pdf-overflow and upload issue

- src/components/Statistics/index.less
https://escl24.atlassian.net/browse/WC-621
> Increase min-width of hall of fame item to prevent premature wrap

- src/pages/Courses/index.tsx
https://escl24.atlassian.net/browse/WC-804
> Remove unnecessary translation

- src/locales/en-US.ts
- src/locales/pl-PL.ts
- src/pages/Users/User/form.tsx
- src/services/escola-lms/user.ts
https://escl24.atlassian.net/browse/IDC-26
> Add return_url parameter to resendEmail() function

- src/components/ProgramForm/ThreeColProgram/TopicForm/index.tsx
- src/components/ProgramForm/ThreeColProgram/TopicForm/media/project.tsx
- src/locales/en-US.ts
- src/locales/pl-PL.ts
- src/services/api.js
- src/services/escola-lms/typings.d.ts
> feat: TopicForm Project

- src/components/Dashboard/YourCourses/index.tsx
[WC-803]
Sort courses data on dashboard by latest.
https://escl24.atlassian.net/browse/WC-803
[WC-803]: https://escl24.atlassian.net/browse/WC-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-803] - Sort courses data on dashboard by latest

- src/pages/Courses/index.tsx
[WC-915]
Fix bug with decimal numbers on courses list.
https://escl24.atlassian.net/browse/WC-915
[WC-915]: https://escl24.atlassian.net/browse/WC-915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-915] - Fix bug with decimal numbers on courses list

- src/components/Dashboard/index.tsx
[WC-930]
Fix error on small devices in welcome dashboard page.
https://escl24.atlassian.net/browse/WC-930
[WC-930]: https://escl24.atlassian.net/browse/WC-930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-930] - Fix error on small devices in welcome dashboard page

- src/components/Dashboard/Tutorial/index.tsx
- src/components/Dashboard/index.css
- src/components/Dashboard/index.tsx
- src/components/Statistics/index.less
- src/components/Statistics/index.tsx
[WC-888]
Change header font size of main box on dashboard.
Change Tutorial box styles and add ProCard wrapper for first text box. Align Statistics to left.
If the content inside the box is larger than the main draggable box, add a scrollbar.
https://escl24.atlassian.net/browse/WC-888
[WC-888]: https://escl24.atlassian.net/browse/WC-888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-888] - dashboard styles update

- src/components/ProgramForm/ThreeColProgram/List/types.tsx
- src/components/ProgramForm/ThreeColProgram/ParentLesson/index.tsx
- src/components/UserGroupSelect/index.tsx
- src/locales/en-US.ts
- src/locales/pl-PL.ts
- src/pages/Users/User/form.tsx
- src/services/escola-lms/user_groups.ts
- fix for project topic type
- fix for root naming in ParentLesson
> feature: EditUser groups

- src/components/AssignQuestionnary/index.tsx
[WC-922]
Add sorting and change id to ID in questionnary table inside course.
https://escl24.atlassian.net/browse/WC-922
[WC-922]: https://escl24.atlassian.net/browse/WC-922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-922] - Add sorting and change id to ID in questionnary table inside course

- src/components/ConsultationRow/index.tsx
- src/components/CourseRow/index.tsx
- src/components/OrderRow/index.tsx
- src/components/ProductRow/index.tsx
- src/components/QuestionnaireRow/index.tsx
- src/components/StationaryEventRow/index.tsx
- src/components/UserGroupRow/index.tsx
- src/components/WebinarRow/index.tsx
- src/locales/en-US.ts
- src/locales/pl-PL.ts
[WC-913]
Handle error messages from not found data in all rows of TypeButton component.
Add translations.
https://escl24.atlassian.net/browse/WC-913
[WC-913]: https://escl24.atlassian.net/browse/WC-913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-913] Handle error messages in TypeButton component.

- src/pages/Vouchers/index.tsx
[WC-867]
Add sorter by id in vouchers table.
https://escl24.atlassian.net/browse/WC-867
[WC-867]: https://escl24.atlassian.net/browse/WC-867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-867] - Add sorter by id in vouchers table.

- src/pages/Products/index.tsx
[WC-869]
Change translation on products page in serach bar from "entity" to "items".
https://escl24.atlassian.net/browse/WC-869
[WC-869]: https://escl24.atlassian.net/browse/WC-869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-869] - Change translation on products page in serach bar from "entity" to "items"

- src/components/ProgramForm/Context/index.tsx
- src/locales/en-US.ts
- src/locales/pl-PL.ts
[WC-855]
Add translations for new title in course program.
https://escl24.atlassian.net/browse/WC-855
[WC-855]: https://escl24.atlassian.net/browse/WC-855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-855] - Add translations for new title in course program

- src/locales/en-US.ts
- src/locales/en-US/courses.ts
- src/locales/fr-FR.ts
- src/locales/fr-FR/courses.ts
- src/locales/pl-PL.ts
- src/locales/pl-PL/courses.ts
- src/pages/Courses/form.tsx
[WC-813]
Add new translations for course form tooltips.
https://escl24.atlassian.net/browse/WC-813
[WC-813]: https://escl24.atlassian.net/browse/WC-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-813] - Add new translations for course form tooltips

- src/pages/Consultations/index.tsx
- src/pages/Pages/index.tsx
[WC-883]
Fix bug with empty name, title or slug field in search bar.
https://escl24.atlassian.net/browse/WC-883
[WC-883]: https://escl24.atlassian.net/browse/WC-883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-883] - Fix bug with empty name, title or slug field in search bar

- src/pages/Products/components/form.tsx
[WC-854]
Change fields width in prices section of product tab.
https://escl24.atlassian.net/browse/WC-854
[WC-854]: https://escl24.atlassian.net/browse/WC-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-854] - Change fields width in prices section of product tab

- src/locales/en-US.ts
- src/locales/fr-FR.ts
- src/locales/pl-PL.ts
- src/pages/Courses/form.tsx
- src/pages/Courses/index.tsx
[WC-805]
Add translations for messages after update, remove, clone and export.
https://escl24.atlassian.net/browse/WC-805
[WC-805]: https://escl24.atlassian.net/browse/WC-805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-805] - Add translations for messages after update, remove, clone and export

- src/components/ProjectsList/index.tsx
- src/locales/en-US.ts
- src/locales/fr-FR.ts
- src/locales/pl-PL.ts
- src/pages/Courses/form.tsx
[WC-852]
Add translations for ProjectsList component.
Add translations for tabs in course form.
https://escl24.atlassian.net/browse/WC-852
[WC-852]: https://escl24.atlassian.net/browse/WC-852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-852] - Add translations for tabs in course form

- src/pages/Courses/form.tsx
[WC-813]
Remove extra text from inputs in course form.
https://escl24.atlassian.net/browse/WC-813
[WC-813]: https://escl24.atlassian.net/browse/WC-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-813] - Remove extra text from inputs in course form

- src/pages/Users/User/form.tsx
[WC-826]
Fix route path after create user.
https://escl24.atlassian.net/browse/WC-826
[WC-826]: https://escl24.atlassian.net/browse/WC-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-826] - Fix route path after create user

- src/pages/Webinars/index.tsx
- src/services/escola-lms/typings.d.ts
[WC-862]
Add sorting in webinars table.
https://escl24.atlassian.net/browse/WC-862
[WC-862]: https://escl24.atlassian.net/browse/WC-862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WC-862] - Add sorting in webinars table

- src/pages/User/login/index.tsx
This fixes [that](https://escl24.atlassian.net/browse/TOS-421) issue.
> bugfix: Custom logo after first login

- src/components/ProgramForm/ThreeColProgram/List/index.css
- src/components/ProgramForm/ThreeColProgram/List/types.tsx
- Change classNames based on 'open' state, which is not the proper react-way solution, but it has to handle css hover as well
> Fix issue with incomplete list of topic types on newly added lesson

- src/components/PdfEditor/index.tsx
- src/components/TemplateFields/index.tsx
- src/pages/Templates/form.tsx
Add onTemplateUpdated in PdfEditor to handle current pdf content.
Show generated pdfs only in edit mode.
Change font to Open Sans in PdfEditor.
https://escl24.atlassian.net/browse/WC-833
> [WC-833] - fix bugs when creating pdfs.

- src/components/ProFormImageUpload/index.tsx
- src/locales/en-US.ts
- src/locales/fr-FR.ts
- src/locales/pl-PL.ts
- src/pages/Categories/components/ModalForm.tsx
Add group props to ProFormImageUpload component.
Add translation for icon.
Hide upload image field when creating new category. Add initial value for switch.
Add custom styles for pro form group in ModalForm component.
https://escl24.atlassian.net/browse/WC-941
> [WC-941] Fix bugs in categories modal.

- src/pages/Translations/admin.tsx
Fix addLocale function in admin Translations component.
https://escl24.atlassian.net/browse/WC-943
> [WC-943] Fix addLocale function in admin Translations component.

- src/components/ProgramForm/Context/index.tsx
Fix bug with deleting new lesson.
https://escl24.atlassian.net/browse/WC-947
> [WC-947] Fix bug with deleting new lesson.

- src/pages/Questionnaire/components/Answers.tsx
- src/pages/Questionnaire/components/Questions.tsx
- src/services/escola-lms/questionnaire.ts
- src/utils/utils.ts
Add sorting and filters to answers and questions tables in Questionnaire component.
Add new sortArrayByKey function in utils.
https://escl24.atlassian.net/browse/WC-952
> [WC-952] Add sorting and filters to answers and questions tables.

- src/pages/Settings/package.tsx
Add sorting and filtering in packages tables on options page.
https://escl24.atlassian.net/browse/WC-954
> [WC-954] Add sorting and filtering in packages tables on options page.

- src/pages/Notifications/index.tsx
Add TypeButtonDrawer for user id in notifications.
https://escl24.atlassian.net/browse/WC-950
> [WC-950] Add TypeButtonDrawer for user id in notifications.

- src/pages/Scorm/preview.tsx
Fix translations and height of container in SCORM preview.
https://escl24.atlassian.net/browse/WC-836
> [WC-836] Fix translations and height of container in SCORM preview.

- src/pages/Courses/index.tsx
- src/services/escola-lms/course.ts
- src/utils/utils.ts
Add createTableOrderObject in utils.
Default sorting courses table list by created_at.
> [WC-966-courses-list] Add createTableOrderObject in utils.

- src/pages/Users/User/form.tsx
- src/services/escola-lms/typings.d.ts
User password is not required if we editing user data.
Check password only if we have value in field.
Remove password from request if password field is empty.
https://escl24.atlassian.net/browse/WC-953
> [WC-953] User password is not required if we editing user data.

- src/pages/Payments/index.tsx
Sort payments table list by "created_at" on default.
> [WC-966-payments-list] Sort payments table list by "created_at" on default.

- src/pages/Categories/index.tsx
- src/services/escola-lms/category.ts
Sort categories table list by "created_at" on default.
> [WC-966-categories-list] Sort categories table list by "created_at" on default.

- src/pages/QuizReports/index.tsx
Sort quiz reports table list by "created_at" on default.
> Sort quiz reports table list by "created_at" on default.

- src/pages/Translations/index.tsx
- src/services/escola-lms/translations.ts
Sort translations table list by "created_at" on default.
> [WC-966-translations-list] Sort translations table list by "created_at" on default.

- src/pages/Users/index.tsx
Sort users table list by "created_at" on default.
> [WC-966-users-list] Sort users table list by "created_at" on default.

- src/pages/Vouchers/index.tsx
Sort vouchers table list by "created_at" on default.
> [WC-966-vouchers-list] Sort vouchers table list by "created_at" on default.

- src/components/UsersSubmissions/index.tsx
- src/locales/en-US.ts
- src/locales/pl-PL.ts
- src/pages/Courses/form.tsx
- src/services/escola-lms/users_submissions.ts
Add sorting in Users Submissions table.
Add default sorting by created_at in Users Submissions table.
Add translations for statuses from Users Submissions table.
Display statuses as Tag in Users Submissions table.
https://escl24.atlassian.net/browse/WC-965
> [WC-965] Add sorting in Users Submissions table.

- src/pages/StationaryEvents/index.tsx
- src/services/escola-lms/stationary_events.ts
Sort stationary events table list by "created_at" on default.
> [WC-966-stationary-events-list] Sort stationary events table list by "created_at" on default.

- src/pages/UserGroups/index.tsx
Sort users groups table list by "created_at" on default.
> [WC-966-groups-list] Sort users groups table list by "created_at" on default.

- src/components/NoticeIcon/index.tsx
- src/pages/Notifications/index.tsx
- src/services/escola-lms/notifications.ts
Sort notifications table list by "created_at" on default.
> [WC-966-notifications-list] Sort notifications table list by "created_at" on default.

- src/pages/Questionnaire/index.tsx
Sort questionnaires table list by "created_at" on default.
> [WC-966-questionnaires-list] Sort questionnaire table list by "created_at" on default.

- src/pages/Pages/index.tsx
- src/services/escola-lms/pages.ts
Sort pages table list by "created_at" on default.
> [WC-966-pages-list] Sort pages table list by "created_at" on default.

- src/components/Footer/index.tsx
- src/pages/Settings/global.tsx
Change Escola Soft to Wellms with new href in footer.
https://escl24.atlassian.net/browse/WC-972
> [WC-972] Change Escola Soft to Wellms with new href in footer.

- src/components/ConfirmModal/index.tsx
- src/hooks/useValidateFormEdit.tsx
- src/locales/en-US.ts
- src/locales/pl-PL.ts
- src/pages/Webinars/form.tsx
Removed UnsavedPrompt component.
Add ConfirmModal component.
Add valuesChanged, showConfirmModal and loading properties in useValidateFormEdit hook.
Add confirmation modal in webinars when user want change tab to products. If user edited fields in other tabs he need save changes. In Products tab is new form.
https://escl24.atlassian.net/browse/WC-992
> [WC-992] Removed UnsavedPrompt component

- src/pages/Consultations/index.tsx
- src/pages/Courses/index.tsx
- src/pages/Orders/index.tsx
- src/pages/Payments/index.tsx
- src/pages/Vouchers/index.tsx
- src/pages/Webinars/index.tsx
- src/utils/utils.ts
Add divider to roundTo function in utils.
Add divider to webinars, vouchers, payments, orders and consultations list.
https://escl24.atlassian.net/browse/WC-981
> [WC-981] Add divider to roundTo function in utils.

- src/components/MoneyInput/index.tsx
- src/pages/Products/components/form.tsx
Add defaultValue prop to MoneyInput because sometimes we need null instead 0.
https://escl24.atlassian.net/browse/WC-1000
> [WC-1000] Add defaultValue prop to MoneyInput

- src/components/ProductsSelect/index.tsx
- src/components/Tags/index.tsx
- src/components/UserSelect/index.tsx
- src/pages/Courses/index.tsx
- src/pages/Webinars/index.tsx
- src/services/escola-lms/typings.d.ts
- src/services/escola-lms/webinars.ts
Add clear and multiple options to Tags component.
Clear selected products, tags and users when we use clear button.
Add WebinarsParams type.
Add multiple tags filtering in webinars and courses.
https://escl24.atlassian.net/browse/WC-864
> [WC-864] Add clear and multiple options to Tags component.

- src/pages/TeacherSubjects/components/Students.tsx
- src/pages/TeacherSubjects/form.tsx
Added filtering by user `first_name`, `last_name` and `email`. Changed way whole table fetches data - simplified code.
> feat: Students table search refactor SUD-172

- src/locales/en-US/consultations.ts
- src/locales/fr-FR/consultations.ts
- src/locales/pl-PL/consultations.ts
- src/pages/Consultations/form.tsx
Add translation for duration tooltip in consultations.
https://escl24.atlassian.net/browse/WELLMS-319
> [WELLMS-319] Add translation for duration tooltip in consultations.

- src/components/MoneyInput/index.tsx
- src/pages/Consultations/form.tsx
- src/pages/Courses/form.tsx
- src/pages/Webinars/form.tsx
add new ConfirmModal component to consultations.
Removed old console.log from MoneyInput.
Fix bug while saving data in Webinars form.
Add ConfirmModal to courses.
https://escl24.atlassian.net/browse/WELLMS-320
> [WELLMS-320] 

- src/pages/Consultations/components/Calendar.tsx
Add sorting to calendar table in consultations.
https://escl24.atlassian.net/browse/WELLMS-315
> [WELLMS-315] Add sorting to calendar table in consultations

- src/components/AttendanceCheckbox/index.tsx
- src/locales/en-US.ts
- src/locales/pl-PL.ts
- src/pages/TeacherSubjects/components/Attendances.tsx
- src/pages/TeacherSubjects/components/ClassRegister.tsx
- src/pages/TeacherSubjects/components/ExamGradeInput.tsx
- src/pages/TeacherSubjects/components/ExamResults.tsx
- src/pages/TeacherSubjects/components/Exams.tsx
- src/pages/TeacherSubjects/components/FileExportsHistory.tsx
- src/pages/TeacherSubjects/components/FinalGradesList.tsx
- src/pages/TeacherSubjects/components/Groups.tsx
- src/pages/TeacherSubjects/components/Students.tsx
- src/pages/TeacherSubjects/components/index.css
- src/pages/TeacherSubjects/form.tsx
- src/services/escola-lms/typings.d.ts
This PR closes part of SUD-190 task.
> feat: Class register SUD-190

- src/components/TypeDrawer/index.tsx
- src/pages/Courses/index.tsx
- src/pages/Products/index.tsx
Hide authors select in descriptions drawer.
Change visible to open (visible its deprecated) in TypeDrawer.
Fix translations in products table.
Sort by default products table by created_at.
https://escl24.atlassian.net/browse/WELLMS-344
> [WELLMS-344] Fix type drawer in products.

- src/services/escola-lms/orders.ts
Fix page param in orders fetching.
https://escl24.atlassian.net/browse/WELLMS-347
> [WELLMS-347-12] Fix page param in orders fetching.

- src/components/ProgramForm/ThreeColProgram/LessonForm/index.tsx
Fix stacking order in lesson program.
https://escl24.atlassian.net/browse/WELLMS-307
> [WELLMS-307] Fix stacking order in lesson program.

- src/components/AuthenticatedLinkButton/index.tsx
- src/locales/en-US.ts
- src/locales/fr-FR.ts
- src/locales/pl-PL.ts
- src/pages/H5P/index.tsx
- src/services/escola-lms/h5p.ts
Updated AuthenticatedLinkButton with try catch and add messages after success or failed download.
Change H5P export button with AuthenticatedLinkButton.
Add translations for download messages.
https://escl24.atlassian.net/browse/WELLMS-180
> [WELLMS-180] Change H5P export button with AuthenticatedLinkButton

- src/components/CourseStatistics/ExportStatsButton.tsx
- src/components/CourseStatistics/index.tsx
- src/components/CourseStatistics/userProgress.tsx
- src/pages/TeacherSubjects/components/FinalGradesDetails/index.tsx
- src/services/escola-lms/reports.ts
- src/services/escola-lms/typings.d.ts
> [WELLMS-21] Export stats button in statistics

- src/pages/Users/index.tsx
- src/services/escola-lms/csv.ts
- src/utils/utils.ts
Add xlsx and xls format in users export.
https://escl24.atlassian.net/browse/WELLMS-182
> [WELLMS-182] Add xlsx and xls format in users export.

- src/components/AttendanceCheckbox/index.tsx
- src/components/AttendanceCheckbox/types.ts
- src/components/AttendanceCheckbox/utils.ts
- src/locales/en-US.ts
- src/locales/pl-PL.ts
- src/pages/TeacherSubjects/components/Attendances.tsx
- src/pages/TeacherSubjects/components/ClassRegister/utils.tsx
- src/services/escola-lms/enums.ts
> feat: AttendanceCheckbox changes SUD-192

- src/components/Footer/index.css
- src/components/Footer/index.tsx
> feat: Footer logo styles SUD-198

- src/pages/Settings/global.tsx
> feat: Technical maintenance

- src/components/ProgramForm/ThreeColProgram/List/LessonList/index.tsx
- src/components/ProgramForm/ThreeColProgram/List/LessonList/utils.ts
- src/locales/en-US.ts
- src/locales/pl-PL.ts
- Topics nesting is now working more UX friendly - user can drop another topic/lesson on topic and the topic/lesson will be moved to topic's parent lesson
- Added support for maxLessonsNestingInProgram & minTopicNestingInProgram settings in program's DND area
> feat: DND refactor WELLMS-377

- src/components/ProgramForm/ThreeColProgram/List/LessonList/index.tsx
- src/components/ProgramForm/ThreeColProgram/List/TopicTypesSelector.tsx
- src/pages/Translations/index.tsx
> Lesson Level transaltions TOS-465

- src/components/CourseStatistics/index.tsx
- src/components/CourseStatistics/userProgress.tsx
- src/pages/Courses/index.tsx
- src/services/escola-lms/typings.d.ts
Fix bug with average time per topic in course statistics.
Add tag "published_unactivated" in courses table.
Fix date format in course statistics table.
Add CourseStatsAverageTimePerTopic type for CourseStats.
Add new types for value in courseStats.
https://escl24.atlassian.net/browse/WELLMS-405
> [WELLMS-405] Fix bug with average time per topic in course statistics.

- config/routes.ts
- src/access.ts
- src/consts/permissions.ts
- src/hooks/usePermissions.ts
- src/locales/pl-PL.ts
- src/locales/pl-PL/bulkNotifications.ts
- src/pages/Courses/index.tsx
- src/pages/Translations/components/ModalForm.tsx
- src/pages/Users/BulkNotifications/List/index.tsx
- src/pages/Users/BulkNotifications/form.tsx
- src/pages/Users/BulkNotifications/index.tsx
- src/services/escola-lms/bulk-notifications.ts
- src/services/escola-lms/enums.ts
- src/services/escola-lms/typings.d.ts
Add usePermissions hook.
Hide import, export and clone buttons in course if user doesn't have permissions. Add public switch in translations modal.
Add bulk notifications panel in users.
> Add bulk notifications panel in users.

- src/components/ProgramForm/Context/index.tsx
Add assistant_id for lesson in course program.
> Add assistant_id for lesson in course program.

- config/routes.ts
- src/access.ts
- src/consts/packages.ts
- src/consts/permissions.ts
- src/locales/pl-PL.ts
- src/pages/Dictionary/components/DictionaryWords/Descriptions/index.tsx
- src/pages/Dictionary/components/DictionaryWords/Descriptions/modal.tsx
- src/pages/Dictionary/components/DictionaryWords/form.tsx
- src/pages/Dictionary/components/DictionaryWords/index.tsx
- src/pages/Dictionary/form.tsx
- src/pages/Dictionary/index.tsx
- src/pages/Settings/global.tsx
- src/services/escola-lms/dictionary.ts
- src/services/escola-lms/typings.d.ts
Add dictionary module.
Add dictionary words module inside dictionary.
Add types for dictionary.
Add permissions for dictionary.
> Add dictionary module.

- src/components/ProFormImageUpload/index.tsx
- src/components/ProFormVideoUpload/index.tsx
- src/components/SecureUpload/browser.tsx
- src/pages/Courses/form.tsx
Fix styles in Media tab in course.
Hide close button on file browser modal.
> Fix styles in Media tab in course.

- src/components/ProgramForm/Context/index.tsx
- src/components/ProgramForm/ThreeColProgram/LessonForm/form.tsx
- src/components/ProgramForm/ThreeColProgram/LessonForm/index.tsx
- src/locales/pl-PL.ts
Add assistant_id boolean in context.
Add assistant_id field in lesson field.
> Add assistant_id field in lesson field.

- src/consts/permissions.ts
- src/global.less
- src/locales/en-US.ts
- src/locales/pl-PL.ts
- src/pages/Categories/index.tsx
- src/pages/Dictionary/components/DictionaryWords/index.tsx
> Add dictionary import

- src/pages/Users/BulkNotifications/form.tsx
Hide redirect and image fields in bulk notifications.
> Hide redirect and image fields in bulk notifications.

- src/components/SecureUpload/browser.tsx
- src/components/SecureUpload/index.tsx
- src/pages/Roles/components/CustomCheckbox/index.tsx
- src/pages/Roles/form.tsx
- src/pages/Users/myProfile.tsx
> Refresh avatar after upload

- src/pages/TeacherSubjects/components/Schedule.tsx
Calendar in Sechdule this is deprecated #1039
> Calendar in Sechdule this is deprecated #1039

- src/components/ProFormImageUpload/index.tsx
- src/components/ProFormVideoUpload/index.tsx
- src/pages/Questionnaire/form.tsx
Fixes #1017 
Fixes #1035 
Fixes #1016
> fix types for image and video upload
